apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minifi-checkpoints
  namespace: ci
  labels:
    app.kubernetes.io/name: minifi-java-parquet-ingestion
    app.kubernetes.io/component: checkpoints
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-ecs-cluster-sc
  resources:
    requests:
      storage: 1Gi